FROM node:18.12.0-alpine

# set working directory
# 작업을 수행할 디렉토리를 지정
WORKDIR /frontend

ENV CHOKIDAR_USEPOLLING=true

COPY package*.json .
# 현재 경로에 있는 것을 frontend로 복사

EXPOSE 5173

RUN npm cache clean --force

RUN npm install --force

COPY . ./

RUN npm run build